### ISSUE TITLE
Feature request: `{ggplot}` implementation of `WeightedCluster::seqnullcqi` plots

### ISSUE THREAD

**Issue by andreasljungstrm** [maraab23/ggseqplot#2]
Currently, plots of cluster quality indices from parametric bootstraps using [`WeightedCluster::seqnullcqi`](https://github.com/cran/WeightedCluster/blob/master/R/seqnullcqi.R) are implemented using R's base plot function. I think it might be a nice addition to `{ggseqplot}` if it could also produce these types of plots using `{ggplot}`.

I am currently using `seqnullcqi` plots in a project, and I will probably rewrite the plotting code using `{ggplot}` for my own work. If it is of interest I can submit it as a pull request to `{ggseqplot}` when it's done.

Cheers!

**Comment by maraab23** [comment]
I agree that it would be nice to add the `WeightedCluster` plots to the package. However, for me this is only a side project (which already took more time than it should have) and I am currently not planning to implement `WeightedCluster` plots. If you indeed wrote some code, feel free to submit it and we could discuss its integration.
